# Data Exploration

A place where I look into the data to see if there's any patterns/for inspiration on how to forecasts.

In [5]:
# imports
import pandas as pd
import pyarrow.parquet as pq

In [6]:
# loading data
# Read the Parquet file
table = pq.read_table("datasets/train.parquet")

# Convert to a pandas DataFrame
df = table.to_pandas()

print("First five data entries:")
print(df.head())

df

First five data entries:
   seq_ix  step_in_seq  need_prediction         0         1         2  \
0       0            0                0 -0.080082  1.324564  0.637730
1       0            1                0 -1.243274  0.398425 -1.810485
2       0            2                0 -0.124680  1.225580  0.139482
3       0            3                0 -1.264455  0.494485 -1.041663
4       0            4                0 -0.882663 -0.223168 -1.229349

          3         4         5         6  ...        22        23        24  \
0 -1.091486 -0.859104  1.291364 -1.046394  ...  0.876881 -1.425938 -0.104571
1 -0.427042  0.303473  0.304587 -0.392796  ...  0.669286 -0.720985 -1.144171
2 -0.967710 -0.769101  1.208697 -1.218701  ...  0.742988 -1.381406  0.043121
3 -0.587907  0.203893  0.437923 -0.479116  ...  0.808542 -0.777047 -1.163911
4  0.029471  0.459377 -0.232340  0.113789  ...  0.286553 -0.114436 -0.730509

         25        26        27        28        29        30        31
0  1.253508 -1.155514 -0.907224  1.361777  0.602751  1.265182 -0.495940
1  0.724269 -1.259564  0.181201  0.529757 -0.076843  1.111895 -1.171435
2  1.205969 -1.062414 -0.739191  1.266046  0.856712  1.205016 -0.417057
3  0.801497 -1.280313 -0.090955  0.636906 -0.213926  1.121746 -1.364489
4  0.301325 -0.782454  0.486104 -0.172012 -0.016936  0.674722 -0.740237

[5 rows x 35 columns]

,seq_ix,step_in_seq,need_prediction,0,1,2,3,4,5,6,...,22,23,24,25,26,27,28,29,30,31
0,0,0,0,-0.080082,1.324564,0.637730,-1.091486,-0.859104,1.291364,-1.046394,...,0.876881,-1.425938,-0.104571,1.253508,-1.155514,-0.907224,1.361777,0.602751,1.265182,-0.495940
1,0,1,0,-1.243274,0.398425,-1.810485,-0.427042,0.303473,0.304587,-0.392796,...,0.669286,-0.720985,-1.144171,0.724269,-1.259564,0.181201,0.529757,-0.076843,1.111895,-1.171435
2,0,2,0,-0.124680,1.225580,0.139482,-0.967710,-0.769101,1.208697,-1.218701,...,0.742988,-1.381406,0.043121,1.205969,-1.062414,-0.739191,1.266046,0.856712,1.205016,-0.417057
3,0,3,0,-1.264455,0.494485,-1.041663,-0.587907,0.203893,0.437923,-0.479116,...,0.808542,-0.777047,-1.163911,0.801497,-1.280313,-0.090955,0.636906,-0.213926,1.121746,-1.364489
4,0,4,0,-0.882663,-0.223168,-1.229349,0.029471,0.459377,-0.232340,0.113789,...,0.286553,-0.114436,-0.730509,0.301325,-0.782454,0.486104,-0.172012,-0.016936,0.674722,-0.740237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516995,516,995,1,-0.637696,-0.938058,-0.717372,0.765730,0.837935,-1.077906,0.665360,...,-0.109771,0.597868,-0.337359,-0.200192,0.029267,0.917658,-1.164635,-0.115904,0.082596,-0.153497
516996,516,996,1,-0.742073,-0.872802,-0.913195,0.667820,0.760674,-1.001379,0.370095,...,-0.072015,0.479413,-0.358344,-0.131352,-0.006000,0.864407,-1.085941,-0.151058,0.047374,-0.274957
516997,516,997,1,-0.627282,-0.947610,-0.704207,0.777083,0.842881,-1.083484,0.691369,...,-0.112420,0.609684,-0.336021,-0.207586,0.032277,0.920959,-1.169182,-0.113311,0.085180,-0.143595
516998,516,998,1,-0.781694,-0.876804,-1.356198,0.876537,0.927931,-1.007557,0.594830,...,-0.164312,0.454387,-0.464434,-0.114372,-0.170993,1.121660,-1.165715,0.081101,0.248766,-0.170322
516999,516,999,0,-0.889236,-0.739815,-1.456582,0.709961,0.840541,-0.841297,0.495999,...,-0.007413,0.278335,-0.574320,0.064692,-0.325771,0.987596,-0.968447,0.126450,0.391151,-0.304556

In [11]:
N = df.shape[1] - 3
FEATURE_COLUMNS = [f"{i}" for i in range(N)]
#print(FEATURE_COLUMNS)

df[FEATURE_COLUMNS]

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,-0.080082,1.324564,0.637730,-1.091486,-0.859104,1.291364,-1.046394,-0.378080,0.282473,1.229306,...,0.876881,-1.425938,-0.104571,1.253508,-1.155514,-0.907224,1.361777,0.602751,1.265182,-0.495940
1,-1.243274,0.398425,-1.810485,-0.427042,0.303473,0.304587,-0.392796,-0.830610,-0.556807,0.801201,...,0.669286,-0.720985,-1.144171,0.724269,-1.259564,0.181201,0.529757,-0.076843,1.111895,-1.171435
2,-0.124680,1.225580,0.139482,-0.967710,-0.769101,1.208697,-1.218701,-0.000233,0.503537,1.196262,...,0.742988,-1.381406,0.043121,1.205969,-1.062414,-0.739191,1.266046,0.856712,1.205016,-0.417057
3,-1.264455,0.494485,-1.041663,-0.587907,0.203893,0.437923,-0.479116,-1.060115,-0.797105,0.840953,...,0.808542,-0.777047,-1.163911,0.801497,-1.280313,-0.090955,0.636906,-0.213926,1.121746,-1.364489
4,-0.882663,-0.223168,-1.229349,0.029471,0.459377,-0.232340,0.113789,-0.550850,-0.323134,0.408995,...,0.286553,-0.114436,-0.730509,0.301325,-0.782454,0.486104,-0.172012,-0.016936,0.674722,-0.740237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516995,-0.637696,-0.938058,-0.717372,0.765730,0.837935,-1.077906,0.665360,-0.119219,-0.121663,-0.343789,...,-0.109771,0.597868,-0.337359,-0.200192,0.029267,0.917658,-1.164635,-0.115904,0.082596,-0.153497
516996,-0.742073,-0.872802,-0.913195,0.667820,0.760674,-1.001379,0.370095,0.000740,-0.099014,-0.292136,...,-0.072015,0.479413,-0.358344,-0.131352,-0.006000,0.864407,-1.085941,-0.151058,0.047374,-0.274957
516997,-0.627282,-0.947610,-0.704207,0.777083,0.842881,-1.083484,0.691369,-0.129949,-0.123029,-0.348357,...,-0.112420,0.609684,-0.336021,-0.207586,0.032277,0.920959,-1.169182,-0.113311,0.085180,-0.143595
516998,-0.781694,-0.876804,-1.356198,0.876537,0.927931,-1.007557,0.594830,0.116927,0.116342,-0.205627,...,-0.164312,0.454387,-0.464434,-0.114372,-0.170993,1.121660,-1.165715,0.081101,0.248766,-0.170322
516999,-0.889236,-0.739815,-1.456582,0.709961,0.840541,-0.841297,0.495999,0.041718,0.064927,-0.057781,...,-0.007413,0.278335,-0.574320,0.064692,-0.325771,0.987596,-0.968447,0.126450,0.391151,-0.304556

In [ ]:
# selecting based on seq_ix
curr_seq_ix = 0

filtered_df = df.loc[df['seq_ix'] == curr_seq_ix]

# output first 10 and last 10 rows to check if they need prediction
print(filtered_df.iloc[99:110, 2])
print(filtered_df.iloc[-10:, 2])

In [ ]:
# checking for missing values
df[df.isnull().any(axis=1)]

In [ ]:
# checking shape
print(df.shape[1])